language: generic

branches:
  only:
    - master

os:
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=""
      osx_image: xcode10
    - env: BUILD_OPTIONS=""
    - env: BUILD_OPTIONS="--build-from-source"
    - env: BUILD_OPTIONS="--with-no-titlebar"
    - env: BUILD_OPTIONS="--devel"
    - env: BUILD_OPTIONS="--without-cocoa"
    - env: BUILD_OPTIONS="--without-cocoa --with-x11"
  fast_finish: true

before_install:
  - brew update

script:
  - travis_wait brew install Formula/emacs-plus.rb $BUILD_OPTIONS
  - brew test Formula/emacs-plus.rb
