name: Emacs 26

on:
  push:
    branches:
      - master
    paths:
      - "Formula/emacs-plus@26.rb"
      - "patches/emacs-26/**"
      - "Library/**"
      - ".github/workflows/emacs-26.yml"
  pull_request:
    paths:
      - "Formula/emacs-plus@26.rb"
      - "patches/emacs-26/**"
      - "Library/**"
      - ".github/workflows/emacs-26.yml"
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        build_opts:
          - ""
          - "--build-from-source"

    env:
      HOMEBREW_EMACS_PLUS_MODE: local

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Build emacs-plus@26 ${{ matrix.build_opts }}
        run: brew install ./Formula/emacs-plus@26.rb ${{ matrix.build_opts }}

      - name: Test installation
        if: contains(matrix.build_opts, '--HEAD') == false
        run: brew test ./Formula/emacs-plus@26.rb

      - name: Test installation (--HEAD)
        if: contains(matrix.build_opts, '--HEAD')
        run: brew test ./Formula/emacs-plus@26.rb --HEAD
