name: Emacs 31

on:
  push:
    branches:
      - master
    paths:
      - "Formula/emacs-plus@31.rb"
      - "patches/emacs-31/**"
      - "Library/**"
      - ".github/workflows/emacs-31.yml"
  pull_request:
    paths:
      - "Formula/emacs-plus@31.rb"
      - "patches/emacs-31/**"
      - "Library/**"
      - ".github/workflows/emacs-31.yml"
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        build_opts:
          - ""
          - "--with-xwidgets"
          - "--with-x11"

    env:
      HOMEBREW_EMACS_PLUS_MODE: local

    steps:
      - uses: actions/checkout@v5

      - name: Install xquartz
        if: contains(matrix.build_opts, '--with-x11')
        run: brew install --cask xquartz

      - name: Build emacs-plus@31 ${{ matrix.build_opts }}
        run: brew install ./Formula/emacs-plus@31.rb ${{ matrix.build_opts }} --verbose

      - name: Test installation
        run: $(brew --prefix)/bin/emacs --batch --eval='(print (+ 2 2))'

      - name: Pack up build logs
        if: ${{ always() }}
        run: |
          BUILD_OPTS=$(echo "${{ matrix.build_opts }}" | sed 's/ //')
          echo "build_opts=$BUILD_OPTS" >> "$GITHUB_ENV"
          RUNNER_OS=$(echo "${{ matrix.os }}" | sed 's/ //')
          echo "runner_os=$RUNNER_OS" >> "$GITHUB_ENV"
          tar -C ~/Library/Logs/Homebrew/emacs-plus@31/ -czvf ~/Library/Logs/Homebrew/emacs-plus@31-$RUNNER_OS$BUILD_OPTS.tar.gz .

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: emacs-plus@31-${{ env.runner_os }}${{ env.build_opts }}.tar.gz
          path: |
            ~/Library/Logs/Homebrew/emacs-plus@31-${{ env.runner_os }}${{ env.build_opts }}.tar.gz
