name: CI

on:
  push:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        build_opts:
          - ''
          - '--build-from-source'
          - '--with-no-titlebar'
          - '--HEAD'
          - '--HEAD --with-xwidgets'
          - '--HEAD --with-emacs-27-branch'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
    - uses: actions/checkout@v1

    - name: Build emacs-plus ${{ matrix.build_opts }}
      run: brew install Formula/emacs-plus.rb ${{ matrix.build_opts }}

    - name: Test installation
      if: contains(matrix.build_opts, '--HEAD') == false
      run: brew test Formula/emacs-plus.rb

    - name: Test installation (--HEAD)
      if: contains(matrix.build_opts, '--HEAD')
      run: brew test Formula/emacs-plus.rb --HEAD
