name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        build_opts:
          - ''
          - '--HEAD'
          - '--HEAD --with-no-titlebar'
          - '--HEAD --with-xwidgets'
          - '--HEAD --with-emacs-27-branch'
          - '--HEAD --with-emacs-27-branch --with-xwidgets'
          - '--HEAD --with-emacs-27-branch --with-no-titlebar'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
    - uses: actions/checkout@v1

    - name: Build emacs-plus ${{ matrix.build_opts }}
      run: brew install Formula/emacs-plus.rb ${{ matrix.build_opts }}

    - name: Test installation
      if: contains(matrix.build_opts, '--HEAD') == false
      run: brew test Formula/emacs-plus.rb

    - name: Test installation (--HEAD)
      if: contains(matrix.build_opts, '--HEAD')
      run: brew test Formula/emacs-plus.rb --HEAD
