name: Online Build

on:
  push:
    branches:
      - master
    paths:
      - "Formula/**"
      - "patches/**"
      - "Library/**"
      - ".github/workflows/online.yml"
  pull_request:
    paths:
      - ".github/workflows/online.yml"
  schedule:
    - cron: "0 */12 * * *"

jobs:
  tap-and-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - name: Tap emacs-plus
        run: brew tap d12frosted/emacs-plus

      - name: Build emacs-plus
        run: brew install emacs-plus

      - name: Test installation
        run: brew test emacs-plus

  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - name: Build emacs-plus
        run: brew install d12frosted/homebrew-emacs-plus/emacs-plus

      - name: Test installation
        run: brew test emacs-plus
